<?php
/******************************************
US English
Admin Category Language
******************************************/

$lang['categories']					= 'Categorías';
$lang['error_must_select']			= 'Debe seleccionar una categoría para organizar';
$lang['error_not_found']			= 'No se encontró la categoría seleccionada.';
$lang['organize_category']			= 'Organizar "%s" categoría';
$lang['organize']					= 'Organizar';
$lang['category_id']				= 'ID';
$lang['category_form']				= 'Formulario de categoría';
$lang['name']						= 'Nombre';
$lang['slug']						= 'Slug';
$lang['description']				= 'Descripción';
$lang['excerpt']					= 'Extracto';
$lang['sequence']					= 'Secuencia';
$lang['image']						= 'Imagen';
$lang['seo_title']					= 'Título SEO';
$lang['meta']						= 'Meta data';
$lang['message_category_saved']		= 'La categoría se ha guardado!';
$lang['error_file_upload']			= '<p>No seleccionó ningún documento para subir.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= 'La categoría se ha eliminado.';
$lang['current_file']				= 'Archivo actual';
$lang['confirm_delete_category']	= 'Está seguro de que quiere eliminar esta categoría?';
$lang['add_new_category']			= 'Añadir nueva categoría';
$lang['top_level_category']         = 'Categoría de primer nivel';
$lang['no_categories']				= 'No hay categorías actualmente';
$lang['attributes']					= 'Atributos';
$lang['seo']						= 'SEO';
$lang['parent']						= 'Parent';
$lang['meta_data_description']		= 'ex. &lt;meta name="descripción” contenido=“Vendemos productos que te ayudan“ /&gt;';
$lang['drag_and_drop']				= 'Arrastre y sully los productos en el orden en el que le gustaría que aparezcan.';
$lang['sku']						= 'SKU';
$lang['price']						= 'Precio';
$lang['sale']						= 'Oferta';
$lang['max_file_size']				= 'Max File Size';